M48
; DRILL file KiCad 10.0.6 date 2026-09-12T03:45:27
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-12T03:45:27-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X36.11Y-98.055
X41.89Y-98.055
T2
X4.875Y-89.6
X4.875Y-96.4
T3
X4.0Y-4.0
X4.0Y-101.0
X92.0Y-4.0
X92.0Y-101.0
M30
