M48
; DRILL file KiCad 10.0.6 date 2026-09-09T22:40:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-09T22:40:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X217.09Y-75.545
X222.87Y-75.545
T2
X206.19Y-78.01
X212.99Y-78.01
T3
X201.83Y-78.71
X225.04Y-45.45
M30
